<a href="https://colab.research.google.com/github/SanthoshKJagadish/TensorFlowBasics/blob/master/TensorFlow_worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensorflow

*   Open source library for graph based numerical computation - Computational graph
*   Low and high level APIs - addition, multiplication and ML models
*   TF 2.0 - Eager execution enabled by default, model building centerd around Keras and Estimators high level APIs  






#### Import tensorflow package

In [0]:
import tensorflow as tf
#tf.enable_eager_execution()



#### Defining 0D, 1D, 2D, 3D tensors - 

In [0]:
#0D Tensor
d0 = tf.ones((1,))

#1D Tensor
d1 = tf.ones((2,))

#2D Tensor
d2 = tf.ones((2,2))

#3D Tensor
d3 = tf.ones((2,2,2))


In [0]:
#print(d0.numpy())
#print()

#print(d1.numpy())
#print() 

#print(d2.numpy())
#print()

#print(d3.numpy())

## *1. Constant* 

- A type of node that can take no inputs, but output values that are stored internally

*   Cannot be used for re-training
*   Can have any dimension





In [0]:
# Example 1

node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)

print(node1, node2)

Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32)


In [0]:
# Example 2 - 2x3 constant

a = tf.constant(3, shape = [2,3])
print(a)

Tensor("Const_2:0", shape=(2, 3), dtype=int32)


In [0]:
# Example 3 - 2x2 constant

b = tf.constant([1,2,3,4], shape = [2,2])
print(b)

Tensor("Const_3:0", shape=(2, 2), dtype=int32)


#### Other types of constants 

tf.constant()          ------        tf. constant([1,2,3,4])

```
```


tf.zeros()                ------        tf.zeros([2,2]) 


```
```

tf.zeros_like()        ------        tf.zeros_like(copying size of input tensor)


```
```


tf.ones()                 ------        tf.ones([2,2])
```
```
tf.ones_like()         ------        tf.ones_like(copying size of input tensor)


```
```


tf.fill()                      ------       tf.fill([3,3], 7)

## *2. Placeholder*

- A placeholder is to accept an external value when provided.
- Eager execution is not possible. Rerun as graph mode instead of eager execution mode

In [0]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

add_node = a+b

add_session = tf.Session()

add_session.run(add_node, {a:[1,3], b:[2,4]})

array([3., 7.], dtype=float32)

## *3. Variables* 

- Variables allow us to add trainable parameters to a graph

*   Data type and shape are fixed
*   Can add new values to the variables as input
*   Can be used for training and modifying graph





In [0]:
# Example 1

# y = wX+b

w = tf.Variable([.3], tf.float32) #need to vary as per optimization
b = tf.Variable([-.3], tf.float32) #need to vary as per optimization 
X = tf.placeholder(tf.float32)

linearEQ = w*X + b

# Initialization of Variables

init = tf.global_variables_initializer()

# Start session 

sessionTF = tf.Session()

sessionTF.run(init)

sessionTF.run(linearEQ, {X:[1,2,3,4]})

array([0.        , 0.3       , 0.6       , 0.90000004], dtype=float32)

In [0]:
# Continuation of Ex 1 - calculation of loss

y = tf.placeholder(tf.float32)

squareError = tf.square(linearEQ - y)

squareLoss = tf.reduce_sum(squareError)

print(sessionTF.run(squareLoss, {X:[1,2,3,4], y:[3,5,-6,10]}))

157.46


In [0]:
# Continuation of Ex 1 - Build gradients to optimize outcome (Gradient Descent)

opt = tf.train.GradientDescentOptimizer(0.01)  # Include learning rate -> 0.01

ObjectiveOfTrainFunction = opt.minimize(squareLoss)

for i in range(1000):
  sessionTF.run(ObjectiveOfTrainFunction, {X:[1,2,3,4], y:[3,5,-6,10]})
  
print(sessionTF.run([w,b]))

[array([1.0000011], dtype=float32), 2.0]


In [0]:
# Example 2

a0 = tf.Variable([1,2,3,4], dtype = tf.float32)
a1 = tf.Variable([5,6,7,8], tf.int16)

b = tf.constant(2.0, tf.float32)

# Compute product

c0 = a0*b
c1 = tf.multiply(a0,b)

print(c0)
print(c1)

Tensor("mul_3:0", shape=(4,), dtype=float32)
Tensor("Mul_4:0", shape=(4,), dtype=float32)


In [0]:
print(a0)

<tf.Variable 'Variable_4:0' shape=(4,) dtype=float32_ref>


## Example to show how multi dimenional arrays work in python



In [0]:
import numpy as np

a = np.array([[[1,2,3],[2,3,4]],[[4,5,6],[5,6,7]]])

print(a.shape)
print()

print(a)
print()

print(a[0,1,0])

(2, 2, 3)

[[[1 2 3]
  [2 3 4]]

 [[4 5 6]
  [5 6 7]]]

2


## Tensor Flow Operations 

- Tensor Flow has a model of computation that revolves around graphs. 
- The tensors sit on edges and tensor flow operations work on nodes


*   Add - add()
*   Multiply - multiply(), matmul()
*   Summing over tensor dimensions - reduce_sum(tensor, dimension)



#### Add Operator - add()


*   add() performers element wise addition with two tensors
*   Element wise addition requires both tensors to have same shape
*   The add() operator is overloaded



In [0]:
# Example for Add()

from tensorflow import constant, add, Session

# 0D Tensors

A0 = constant([1])
B0 = constant([2])

#1D Tensors

A1 = constant([1,2])
B1 = constant([3,4])

#2D Tensors

A2 = constant([[1,2], [3,4]])
B2 = constant([[5,6], [7,8]])


c0 = add(A0,B0)
c1 = add(A1,B1)
c2 = add(A2,B2)

sessionTF = Session()

print(sessionTF.run(c0))
print()

print(sessionTF.run(c1))
print()

print(sessionTF.run(c2))

[3]

[4 6]

[[ 6  8]
 [10 12]]


#### Multiply Operator - matmul(), multiply()


*   matmul() performers matrix wise multiplication with two tensors
*   multiply() performs element wise multiplication with two tensors
*   matrix wise multiplication requires number of columns in tensor 1 equal to number of rows in tensor 2

In [0]:
# Example for matmul()

from tensorflow import ones, matmul, multiply


# Define tensors

A0 = ones(1)
A31 = ones([3,1])
A34 = ones([3,4])
A43 = ones([4,3])


b0 = multiply(A0,A0)
print(sessionTF.run(b0))
print()

b31 = multiply(A31,A31)
print(sessionTF.run(b31))
print()

b4334 = matmul(A43, A34)
print(sessionTF.run(b4334))
print()

[1.]

[[1.]
 [1.]
 [1.]]

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]



#### Reduced Sum Operator - reduce_sum()



*   Reduce_sum() operator sums over the dimensions of a tensor
*   reduce_sum(A) - sums over all dimensions of matrix A
*   reduce_sum(A,i) - sums over dimensions of i on matrix A




In [0]:
#Example for reduce_sum

from tensorflow import ones, reduce_sum, Session

A0 = ones([2,3,4]) # 2x3x4 Tensor containing ones

sessionTF = Session()

print(sessionTF.run(A0))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [0]:
sessionTF.run(A0[1][2][1])


1.0

In [0]:
B0 = reduce_sum(A0)

print(sessionTF.run(B0))

24.0


In [0]:
B1 = reduce_sum(A0,0)

print(sessionTF.run(B1))

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [0]:
B2 = reduce_sum(A0,1)

print(sessionTF.run(B2))

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [0]:
B3 = reduce_sum(A0,2)

print(sessionTF.run(B3))

[[4. 4. 4.]
 [4. 4. 4.]]


### Overview of advanced operations



*   gradient() - Computes slope of a function
*   reshape() - Reshapes a tensor
*   random() - Populates tensor with entries drawn from a probability distribution


### Gradient - Finding the optimum

##### Find optimum of a function 
  -  Minimum:  Lowest value of a loss function
  -  Maximum: Highest value of objective function
* Optimal - gradinet = 0 
* Minimum - gradient < 0
* maximum - gradient > 0 

In [0]:
import tensorflow as tf

# define x

x = tf.constant(-1.0)

init = tf.global_variables_initializer()


sessionTF = tf.Session()


sessionTF.run(init)

sessionTF.run(x)

-1.0

In [0]:
# define y

with tf.GradientTape(persistent = True) as tape:
  tape.watch(x)
  y = tf.multiply(x,x)
  print(sessionTF.run(y))

1.0


In [0]:
# Evaluate gradient of y at x = -1

g = tape.gradient(y,x)

print(sessionTF.run(g))

-2.0


### Random and Reshape 

reshape the image to fit the the algorithm


In [0]:
# Example for random and reshape

#Gray image example

import tensorflow as tf

gray = tf.random.uniform([2,2], maxval = 255, dtype = 'int32')

#Reshape

gray = tf.reshape(gray, [2*2,1])

print(gray)

print(tf.Session().run(gray))

Tensor("Reshape_3:0", shape=(4, 1), dtype=int32)
[[ 69]
 [148]
 [ 20]
 [128]]


In [0]:
#Color (RGB) image example

import tensorflow as tf

color = tf.random.uniform([2,2,3], maxval = 255, dtype = 'int32')

#Reshape

color = tf.reshape(color, [2*2,3])

print(color)

print(tf.Session().run(color))

Tensor("Reshape_5:0", shape=(4, 3), dtype=int32)
[[167 178 209]
 [229  17  52]
 [ 77 108 232]
 [ 22 145  55]]


## Importing data 

### Importing data using pandas

In [7]:
import numpy as np
import pandas as pd

housingData = pd.read_csv('kc_house_data.csv')

housingData.head()

id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]